quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/books-db

quarkus.http.port=8070

quarkus.stork.books-api.service-discovery.type=consul
quarkus.stork.books-api.service-discovery.consul-host=127.0.0.1
quarkus.stork.books-api.service-discovery.consul-port=8500
quarkus.stork.books-api.load-balancer.type=round-robin
